---
- name: Update Server
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400 # One day
      # ansible.builtin.apt:
      #  update_cache: true
