---
- name: Update Cloudflare
  hosts: dell
  tasks: 
    - name: Mettre a jour le tunnel Cloudflared
      ansible.builtin.shell: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb &&
        sudo dpkg -i cloudflared.deb &&
        sudo systemctl restart cloudflared
