---
- name: Update Cloudflare
  hosts: cloudflare
  become: true
  tasks:
    - name: Effacer cloudflared.deb
      ansible.builtin.shell: |
        sudo rm cloudflared.deb
      changed_when: false
    - name: Get cloudflared-linux-amd64.deb
      ansible.builtin.uri:
        url: 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb'
        method: GET
        dest: cloudflared.deb
        follow_redirects: safe
        # status_code:
        #   - 200
        #   - 304
      register: result
    - name: Mettre a jour le tunnel Cloudflared
      ansible.builtin.shell: |
        sudo dpkg -i cloudflared.deb &&
        sudo systemctl restart cloudflared
      #  && sudo rm cloudflared.deb
      when: result == true
