---
- name: Update Server
  hosts: pve
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400 # One day
    - name: Vérification du reboot_required
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/rebbot-required
    - name: Lancement du reboot avec reboot
      ansible.builtin.reboot:
        msg: "Reboot via ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
