---
- name: Update Cloudflare
  hosts: cloudflare
  become: true
  tasks:
    - name: Get cloudflared-linux-amd64.deb
      ansible.builtin.uri:
        url: 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb'
        method: GET
        dest: cloudflared.deb
        follow_redirects: safe
      register: result
    - name: Mettre a jour le tunnel Cloudflared
      ansible.builtin.shell: |
        sudo dpkg -i cloudflared.deb &&
        sudo systemctl restart cloudflared
      changed_when: false
